export const FETCH_EXPERIMENTS = 'FETCH_EXPERIMENTS';

export const FETCH_EXPERIMENT = 'FETCH_EXPERIMENTS';
export const ADD_EXPERIMENT = 'ADD_EXPERIMENT';
export const UPDATE_EXPERIMENT = 'UPDATE_EXPERIMENT';
export const DELETE_EXPERIMENT = 'DELETE_EXPERIMENT';