export const FETCH_EXPERIMENTS = 'FETCH_EXPERIMENTS';
export const SEARCH_EXPERIMENTS = 'SEARCH_EXPERIMENTS';

export const FILTER_EXPERIMENTS = 'FILTER_EXPERIMENTS';

export const FETCH_EXPERIMENT = 'FETCH_EXPERIMENT';
export const ADD_EXPERIMENT = 'ADD_EXPERIMENT';
export const EDIT_EXPERIMENT = 'EDIT_EXPERIMENT';
export const DELETE_EXPERIMENT = 'DELETE_EXPERIMENT';

//TOOLS
export const FETCH_TOOLS = 'FETCH_TOOLS';
export const SEARCH_TOOLS = 'SEARCH_TOOLS';

export const FILTER_TOOLS = 'FILTER_TOOLS';

export const FETCH_TOOL = 'FETCH_TOOL';
export const ADD_TOOL = 'ADD_TOOL';
export const EDIT_TOOL = 'EDIT_TOOL';
export const DELETE_TOOL = 'DELETE_TOOL';

