export const FETCH_EXPERIMENTS = 'FETCH_EXPERIMENTS';
export const SEARCH_EXPERIMENTS = 'SEARCH_EXPERIMENTS';

export const FILTER_TOOLS = 'FILTER_TOOLS';

export const FETCH_EXPERIMENT = 'FETCH_EXPERIMENT';
export const ADD_EXPERIMENT = 'ADD_EXPERIMENT';
export const EDIT_EXPERIMENT = 'EDIT_EXPERIMENT';
export const DELETE_EXPERIMENT = 'DELETE_EXPERIMENT';

